language: bash
matrix:
  include:
    - name: Linux Ubuntu 16 - g++ 5
      os: linux
      dist: xenial
      compiler: gcc
      script:
        - python waf build -v
        - python waf --run_tests --run_cmd="%s --arch=x86_64 --compiler=gcc --os=linux"
    - name: Linux Ubuntu 18 - g++ 7
      os: linux
      dist: bionic
      compiler: gcc
      script:
        - python waf build -v
        - python waf --run_tests --run_cmd="%s --arch=x86_64 --compiler=gcc --os=linux"
    - name: Linux Ubuntu 18 - clang 7
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CXX=clang++
      script:
        - python waf build -v
        - python waf --run_tests --run_cmd="%s --arch=x86_64 --compiler=clang --os=linux"
    - name: MacOSX 10.14 - XCode 11
      os: osx
      osx_image: xcode11
      compiler: clang
      script:
        - python waf build -v
        - python waf --run_tests --run_cmd="%s --arch=x86_64 --compiler=clang --os=mac"
    - name: Windows - Visual Studio 2017
      os: windows
      install:
        # git bash changes the codepage to 65001 which breaks waf's msvc tool,
        # so we run the configure step in powershell using the 850 codepage
        - powershell "chcp 850; python waf configure"
      script:
        - python waf build -v
        - python waf --run_tests --run_cmd="%s --arch=x86_64 --compiler=msvc --os=windows"
install:
  - python waf configure

